# Write your query or mutation here
query League($league_id: ID!) {
	league(id: $league_id) {
		id
		name
		status
		events {
			sessions {
				id
				sessionType
			}
			id
			name
			track {
				country
				name
			}
			championshipOrder
			date
		}
		wdcLeaderboard {
			user {
				name
				nationality
			}
			team {
				name
			}
			points
		}
	}
}
